# Generated by Django 4.1 on 2023-07-25 00:48

from django.db import migrations, models
import fomrulaire.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('prenom', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('adress', models.CharField(max_length=70)),
                ('phone1', models.CharField(max_length=8, validators=[fomrulaire.models.is_number])),
                ('phone2', models.CharField(max_length=8, validators=[fomrulaire.models.is_number])),
                ('etat_civil', models.CharField(blank=True, choices=[('a', 'أعزب/عزباء'), ('b', 'متزوج/متزوجة'), ('c', 'مطلق/مطلقة')], default='a', max_length=1)),
                ('etat_santé', models.CharField(blank=True, choices=[('a', 'صحة جيدة'), ('b', 'معاق'), ('c', 'مرض مزمن ')], default='b', max_length=1)),
                ('nb_enfants_scolaire', models.IntegerField(blank=True, null=True)),
                ('nb_enfants_chomeur', models.IntegerField(blank=True, null=True)),
                ('nb_enfants_handicapés', models.IntegerField(blank=True, null=True)),
                ('nb_enfants_totales', models.IntegerField(blank=True, null=True)),
                ('comme_familles', models.CharField(blank=True, choices=[('a', 'الأب والأم'), ('b', 'الخال أو الخالة'), ('c', 'العم أو العمة '), ('d', 'أخر')], default='a', max_length=1)),
                ('revenu_total', models.CharField(blank=True, choices=[('a', 'راتب الشهري '), ('b', 'منحة')], default='a', max_length=1)),
                ('couverture_social', models.TextField(choices=[('y', 'yes'), ('n', 'no')], max_length=1)),
                ('couverture_social_liste', models.CharField(blank=True, choices=[('a', 'راتب الشهري '), ('b', 'منحة')], default='y', max_length=1)),
                ('local', models.CharField(blank=True, choices=[('a', 'راتب الشهري '), ('b', 'منحة')], default='a', max_length=1)),
                ('etat_local', models.CharField(blank=True, choices=[('a', 'راتب الشهري '), ('b', 'منحة')], default='a', max_length=1)),
                ('depense', models.CharField(choices=[('a', 'راتب الشهري '), ('b', 'منحة')], max_length=5)),
                ('evaluation', models.TextField(choices=[('a', 'راتب الشهري '), ('b', 'منحة')], default='a', max_length=1)),
            ],
        ),
    ]
