# Generated by Django 4.1 on 2023-07-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fomrulaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
