# Generated by Django 4.1 on 2023-07-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fomrulaire', '0002_famille_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
