# Generated by Django 4.1 on 2023-07-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fomrulaire', '0003_alter_famille_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
