# Generated by Django 4.1 on 2023-07-25 23:28

from django.db import migrations, models
import fomrulaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('fomrulaire', '0004_alter_famille_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='nb',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='famille',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='famille',
            name='phone2',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[fomrulaire.models.is_number]),
        ),
    ]
