# Generated by Django 4.1 on 2023-07-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fomrulaire', '0005_famille_nb_alter_famille_id_alter_famille_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='famille',
            name='depense',
            field=models.CharField(choices=[('a', 'مصاريف علاج'), ('b', 'مصاريف دراسة '), ('c', 'خلاص الماء '), ('d', 'كهرباء '), ('e', 'معلوم الكراء')], max_length=5),
        ),
        migrations.AlterField(
            model_name='famille',
            name='etat_local',
            field=models.CharField(blank=True, choices=[('a', 'ملكية فردية'), ('b', 'ملكية فردية')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='famille',
            name='local',
            field=models.CharField(blank=True, choices=[('a', 'ملكية فردية'), ('b', 'ملكية فردية')], default='a', max_length=1),
        ),
    ]
