# Generated by Django 4.1 on 2023-09-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fomrulaire', '0007_famille_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='nb_enfants_chomeur',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='famille',
            name='nb_enfants_handicapés',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='famille',
            name='nb_enfants_scolaire',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='famille',
            name='nb_enfants_totales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
