# Generated by Django 4.1 on 2023-09-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fomrulaire', '0009_famillelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilleLog',
        ),
    ]
